In [1]:
import numpy as np

In [3]:
array1 = np.array([1, 3, 5, 6, 7, 9])
array1

array([1, 3, 5, 6, 7, 9])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(4, 17, 3)

array([ 4,  7, 10, 13, 16])

In [9]:
type(array1)

numpy.ndarray

In [12]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
array1.size

6

In [14]:
array2.size

12

In [15]:
array2.shape

(3, 4)

In [16]:
bitcoin_array = np.array([970, 1180, 1072, 1348, 2286, 2481,
                          2875, 4703, 4339, 6468, 10234, 14156])

In [18]:
bitcoin_array[6:9]

array([2875, 4703, 4339])